---
title: "Resume"
---

# Education

AUG 2024 - EXPECTED GRADUATION MAY2025:MASTER OF GEOMATICS IN ENVIRONMENTAL MANAGEMENT, UNIVERSITY OF BRITISH COLUMBIA (CANADA)

OCT 2016 – DEC 2020: BACHELOR OF SCIENCE IN GEOMATICS, ARDHI UNIVERSITY (TANZANIA)

# Publications

*Reports:*

Comparison between Sentinel 2 and Landsat imagery in mapping mangrove using GEM v2 in The Gambia

Evaluation of recent Global Gravity Models (GGMs) Over Tanzania using ground gravity

# Technical Assistantships

-   Supervised surveying field practical for the undergraduate students in the school of Spatial Planning and Construction at Ardhi University.

# Institutional Service

-   I worked as a supporting technical team to process satellite images, develop spatial databases, compose thematic maps of potential restoration areas and support participatory mapping exercises to identify potential restoration opportunities at Global Monitoring for Environment and Security in Africa
-   Assist in Swahili event at Swahili Vision International Association (SVIA) in Canada.
